FROM node:22.12-alpine3.20
# Instala dependencias necesarias
RUN apk add --no-cache libc6-compat openssl
# Crea el directorio de la app
WORKDIR /app
# Copia archivos de configuración e instala dependencias
COPY package.json package-lock.json ./
RUN npm install

# Copia el resto de los archivos al contenedor
COPY . .

EXPOSE 3000

# Comando de inicio
CMD ["npm", "run", "dev"]